### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by adminlove520** [JS-banana/notify-server#11]
为啥配置了天行key但是还是接受不到呢？sercert和.env都配置了的
日志：
config {
  url: 'http://api.tianapi.com/tianqi/index',
  params: { city: '芜湖', key: '***' },
  method: 'GET'
}
errError: timeout of 30000ms exceeded
undefined

**Comment by JS-banana** [comment]
> 为啥配置了天行key但是还是接受不到呢？sercert和.env都配置了的 日志： config { url: 'http://api.tianapi.com/tianqi/index', params: { city: '芜湖', key: '***' }, method: 'GET' } errError: timeout of 30000ms exceeded undefined

哈喽~

首先排查网络问题，看错误信息像是接口超时错误导致的。参考我的配置调试下，我的脚本目前是一直正常运行的。

可以先在 ,env 文件配置相关变量 (,env文件只在本地开发环境使用)，然后本地调试下接口看下返回结果是否正常

GitHub sercert 变量是提供脚本在GitHub action脚本服务的（可以理解为线上环境）
