### ISSUE TITLE
BUG反馈

### ISSUE THREAD

**Issue by Mortal520** [JS-banana/notify-server#13]
大哥，这个项目是个半成品吧，而且还咕了好长时间，反馈几个bug

**Comment by Mortal520** [comment]
1、config配置文件内，爱称，自称，农历开关配置无效，看了下，爱称、自称这里你写死了，并没有调用这个配置，农历的没看懂(我只是个没有编程能力的小白)；
2、文本模板里工作日判断，if和else写反了

**Comment by Mortal520** [comment]
然后是一些建议/功能需求。
1、企业微信推送这里，你设置的是@all，建议这里添加配置项，可以自定义，毕竟不是所有人企业微信里面都是只有TA
2、希望增加生日倒计时功能并在卡片消息内输出

**Comment by JS-banana** [comment]
你好，针对你上述的问题我这里做下统一回复：

1. 本项目是在我的真实使用场面下开发而来，也是测试和迭代过多次的，核心功能是经过验证的，当然也不排除在使用过程中未覆盖到的一些问题，不过对于“半成品”的定义我是不认可的。
2. 此项目属于我个人工作之余维护的项目，也符合个人兴趣，因此，我对于此项目投入关注度还是有一定保障的，不过，存在工作因素，也不能保证给予一些同学立即回复，望理解~
3. if else这里可根据自身情况调整，我这里目前逻辑就是这样的，事实也是如此
4.  配置文件无效问题（早安卡片目前正常），目前是拓展信息内容这里没有加载 `config.yml`文件，我会在稍后更新，请关注更新，感谢反馈~
5. 功能建议方面对于通用类功能我会考虑集成进去，不过对于个人定制方面的，需要结合个人情况看，生日倒计时可以采纳，具体形式容我思考下，我在想倒数一个月才开始展示应该更好，可以做成定制
6. 企业微信@all，代码层面是做了兼容的，可以指定id，不过也受企业微信的后台配置影响，即，配置成员必须包含在内

@Mortal520 欢迎一起讨论交流~

**Comment by JS-banana** [comment]
> 1、config配置文件内，爱称，自称，农历开关配置无效，看了下，爱称、自称这里你写死了，并没有调用这个配置，农历的没看懂(我只是个没有编程能力的小白)； 2、文本模板里工作日判断，if和else写反了

已更新，详情见 https://github.com/JS-banana/notify-server/commit/adf87fc04c78547fbd7070be01b1e147b6a4b856

**Comment by Mortal520** [comment]
你好，感谢你能在拨冗阅读我提出的issue。
       首先，我对我之前不太严谨的发言向你道歉，“半成品”只是我的戏言，希望你不要放在心上，此项目的核心功能的简洁稳定，我们也是一致认同的。
       其次，关于代码的问题，由于本人初学编程，对代码的理解尚且不足，所以在BUG的反馈可能并不准确，还请海涵。
      if else这里，根据我的实际情况，周二睡懒觉不太现实，所以感觉这里存在问题/(ㄒoㄒ)/~~。但是，在代码上，我尊重你的逻辑。另外，文本模板的week参数的传递可能存在问题，望检查，详见图一。
     关于企业微信id，由于部分企业微信用户账号为本人姓名缩写，此时如果修改代码并通过GitHub action执行，可能存在隐私泄露风险，所以希望此处能通过secrets传递参数。
     最后，再次感谢你能拨冗阅读我的issue并接纳我的建议&反馈。
![image](https://user-images.githubusercontent.com/72114014/186352754-574fea8f-bf59-493c-90aa-5f77ff0f1987.png)

**Comment by JS-banana** [comment]
> 

哈哈哈，好的，感谢你提出的问题，相关bug我会抽时间进行处理~ 请保持关注进行更新同步~

1. if else 这里的疑问，我这样和你说：你就理解我女朋友是双休上班，工作日休息就行啦，哈哈😁
2. 隐私性的问题我会再研究下，这也是我比较关注和持续做的点，目前关键参数都已通过环境变量处理了

因为本项目最开始只是一个创意Idea项目，对于非技术人员考虑的并不充分，不过，我也在之前进行过一些低成本上手的迭代更新，总的来说，目前这个项目对用户的技术要求已经很低了（基本上完成对应配置之后就能实现发消息的功能了），但是，也有例外，就是每个人的需求和使用场景都有所不同，因此针对你提出的一些问题我也进行了思考，接下来我有计划打算对该项目进行进一步升级迭代，也希望大家一起参与讨论，共同学习🤗

需求建议可以在这里添加：https://github.com/JS-banana/notify-server/issues/14
