### ISSUE TITLE
新版本问题

### ISSUE THREAD

**Issue by lingluan5210** [JS-banana/notify-server#28]
作者能否把新版本的安装过程做到项目主页上，我安装过后还是出现原来的样式，没出现新增的女朋友和男朋友的生日，还想问一下怎么解决，能否写在项目主页上

**Comment by JS-banana** [comment]
> 作者能否把新版本的安装过程做到项目主页上，我安装过后还是出现原来的样式，没出现新增的女朋友和男朋友的生日，还想问一下怎么解决，能否写在项目主页上

主要就是更新了代码，增加了一些功能，其实你直接把最新的代码下载下来就可以了，然后保留你的配置，针对我更新的配置再手动调整添加就行
