### ISSUE TITLE
wx:信息发送成功！ { errcode: 40014, errmsg: 'invalid access_token' }

### ISSUE THREAD

**Issue by TeQuieroS** [JS-banana/notify-server#43]
GitHub Actions 
wx:信息发送成功！ {
  errcode: 60020,
  errmsg: 'not allow to access from your ip, hint: [1681069200365201005041566], from ip: 40.77.50.160, more info at https://open.work.weixin.qq.com/devtool/query?e=60020'
}

**Comment by JoeSmiles** [comment]
这种方式已经不可行了 看下面帖子 大佬有讲怎么用云函数部署 个人觉得这个方案挺不错的

**Comment by JS-banana** [comment]
> GitHub Actions wx:信息发送成功！ { errcode: 60020, errmsg: 'not allow to access from your ip, hint: [1681069200365201005041566], from ip: 40.77.50.160, more info at https://open.work.weixin.qq.com/devtool/query?e=60020' }

因为企业微信可信ip问题的限制，现在不支持了😅，fuck！

**Comment by TeQuieroS** [comment]
腾讯云函数部署
未在根目录下找到函数执行入口文件,请确认代码包入口文件名和 handler 设置是否对
