### ISSUE TITLE
大佬您好；未收到企业微信的消息

### ISSUE THREAD

**Issue by yonghui666** [JS-banana/notify-server#7]
<img width="738" alt="image" src="https://user-images.githubusercontent.com/49012394/153344990-d15e3e0b-b5ef-48ef-9f1b-04cd28acd825.png">
天行api已获取数据；企业微信app已经设置可以微信接收；企业微信后台也设置了允许用户微信内接收信息；运行也没有报错

**Comment by JS-banana** [comment]
你看下企业微信接口返回的数据打印是不是异常的，成功返回值是“OK”，其他是异常情况，考虑你环境变量的值配置是否正确，粘贴的时候不可带有空格~

**Comment by JS-banana** [comment]
囧，我测试功能忘记这个注释了🥲，你把 goodMorning.ts文件 `// import { wxNotify } from '../WxNotify'` 方法 `wxNotify` 开启

**Comment by yonghui666** [comment]
> 囧，我测试功能忘记这个注释了🥲，你把 goodMorning.ts文件 `// import { wxNotify } from '../WxNotify'` 方法 `wxNotify` 开启

已经OK了；非常感谢哈；挺厉害的；值得学习
